language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- mongodb
- memcached
cache: pip
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e1503200bd19_key -iv $encrypted_e1503200bd19_iv
  -in keyfile.pem.enc -out keyfile.pem -d
- pip install --upgrade pytest
- pip install coveralls tox-travis
install:
- pip install -r test_requirements.txt
script: tox -x
after_success:
- coveralls
