language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- mongodb
- memcached
env:
  - TEST_SUITE=tests/dlkit/
  - TEST_SUITE=tests/functional/
  - TEST_SUITE=tests/other/
  - TEST_SUITE=tests/records/
  - TEST_SUITE=tests/assessment/
  - TEST_SUITE=tests/assessment_authoring/
  - TEST_SUITE=tests/authorization/
  - TEST_SUITE=tests/cataloging/
  - TEST_SUITE=tests/commenting/
  - TEST_SUITE=tests/grading/
  - TEST_SUITE=tests/learning/
  - TEST_SUITE=tests/logging_/
  - TEST_SUITE=tests/repository/
  - TEST_SUITE=tests/resource/
  - TEST_SUITE='not tests'
cache: pip
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e1503200bd19_key -iv $encrypted_e1503200bd19_iv
  -in keyfile.pem.enc -out keyfile.pem -d
- pip install --upgrade pytest
- pip install coveralls
install:
- pip install -r test_requirements.txt
script: "python -m pytest -x -k \"$TEST_SUITE\""
after_success:
- coveralls
