language: python
python:
- '2.7'
services:
- mongodb
- memcached
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_e1503200bd19_key -iv $encrypted_e1503200bd19_iv
  -in keyfile.pem.enc -out keyfile.pem -d
- pip install --upgrade pytest
- pip install coveralls
install:
- pip install -r test_requirements.txt
script: python -m pytest -x
after_success:
- coveralls
